name: Upload/Download
on:
  push:
    branches: ['main']
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create Build
        run: |
          mkdir -p build
          echo "This is the sample artifact content" > build/output.txt

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact
          path: build/
