name: Java CI with Maven

env:
  NAME: 'My Action'

on:
  push:
   branches: [ "main" ]

jobs:
  build:
    env: 
      JAVA_VERSION: '11'

    runs-on: ubuntu-latest
    
    steps: 
      - uses: actions/checkout@v3
      - name: Set up JDK ${{env.JAVA_VERSION}}
        uses: actions/setup-java@v3
        with:
          java-version: ${{env.JAVA_VERSION}}
          distribution: 'temurin'
          cache: maven
