name: Test Workflow

env:
 NAME: 'xxx'

on:
 push: 
  branches: ['main']

jobs:
 job1:
  env:
   PLACE: 'London'
  runs-on: ubuntu-latest
  
  steps:
   - name: Echoing ENV Variables on Job1
     run: echo "My Names is $NAME Living in $PLACE"

 job2:
  env:
   FN: 'YYY'
   NAME: ${{ env.FN }}
  runs-on: ubuntu-latest
  steps:
   - name: Echoing ENV Variables on Job2
     run: echo "My Name is $NAME living in $PLACE"
     env:
      PLACE: 'LONDON'
    

  
  
