name: Secret Finder
on: workflow_dispatch
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: My Secret Expose
        run: echo "The Secret Stored Inside MYSECRET is ${{secrets.MYSECRET}}" > secret.txt

      - name: Upload Secret as artifact
        uses: actions/upload-artifacts@4
        with:
          name: secret_file
          path: secret.txt
